# Stage 1: Build the application
FROM python:3.9-slim AS build

# Set the working directory
WORKDIR /app

# Copy the requirements file
COPY requirements.txt .

# Install the dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Copy the application code
COPY . .

# Stage 2: Run the application
FROM python:3.9-slim

# Set the working directory
WORKDIR /app

# Copy the installed dependencies from the build stage
COPY --from=build /usr/local/lib/python3.9/site-packages /usr/local/lib/python3.9/site-packages

# Copy the application code from the build stage
COPY --from=build /app .

# Set the environment variable for Flask
ENV FLASK_APP=app.py
ENV FRONTEND_URL="*"
ENV BACKEND_URL="*"


# Expose the port for the Flask application
EXPOSE 4567

# Run the Flask application
CMD ["flask", "run", "--host=0.0.0.0"]
