# Stage 1: Build the application
FROM python:3.9-slim AS build

# Set the working directory
WORKDIR /backend-flask

# Copy the requirements file
COPY requirements.txt .

# Install the dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Copy the application code
COPY . .

# Stage 2: Run the application
FROM python:3.9-slim

# Set the working directory
WORKDIR /backend-flask

# Copy the installed dependencies from the build stage
COPY --from=build /usr/local/lib/python3.9/site-packages /usr/local/lib/python3.9/site-packages

# Copy the application code from the build stage
COPY --from=build /backend-flask .

# Set the environment variable for Flask
ENV FLASK_APP=app.py

# Expose the port for the Flask application
EXPOSE 4567

# Run the Flask application
CMD [ "python3", "-m" , "flask", "run", "--host=0.0.0.0", "--port=4567"]
